### ISSUE TITLE
Dropdown doesn't appear to close old menus when opening another

### ISSUE THREAD

**Issue by mmastrac** [sakofchit/system.css#1]
First of all, beautiful library!

I'm not sure if this is by design, but the menus don't close when another menu opens.

<img width="550" alt="image" src="https://user-images.githubusercontent.com/512240/184265983-d9e69f69-42ec-4bb9-92b3-7030c425cb30.png">

**Comment by sakofchit** [comment]
Definitely not intentional, will push out a fix in a bit!

**Comment by KunalTanwar** [comment]
I see you haven't use any JavaScript!! Curios because I want to contribute in this issue specifically

**Comment by KunalTanwar** [comment]
> First of all, beautiful library!
> 
> I'm not sure if this is by design, but the menus don't close when another menu opens.
> 
> <img alt="image" width="550" src="https://user-images.githubusercontent.com/512240/184265983-d9e69f69-42ec-4bb9-92b3-7030c425cb30.png">

Until @sakofchit is not pushing the fix you can check this [Codpen](https://codepen.io/KunalTanwar/pen/wvmQjVK) I replicate the **UI** (even then just use the `JS` code) and added the functionality.

**Comment by sakofchit** [comment]
Hi! this should be fixed now: https://sakofchit.github.io/system.css/#menu-bar
