### ISSUE TITLE
Working on fixing the layout

### ISSUE THREAD

**Issue by Preet-Sojitra** [sakofchit/system.css#11]
Hey @sakofchit , I was working on fixing the layout of the website, as it is messed up ( Issue #3 ) . So for this I am planning to change the html structure little bit. 
I am planning to wrap the `aside` and `main` in one container and want to make it a grid. 
Here's the [codepen](https://codepen.io/preetsojitra/pen/poLXQOE?editors=1100).

In this codepen I have created the rough layout . You can see the html structure in the codepen that I am planning to implement in the system.css

So should I change the HTML structure?

**Comment by sakofchit** [comment]
Was actually working on this last night! That would work too, but my approach was to just use flexbox since it's only really just 2 columns. #12 

https://user-images.githubusercontent.com/7917503/187243046-0c5f79a3-96a0-42f6-891f-644017281328.mp4

**Comment by Preet-Sojitra** [comment]
LGME 🚀
