### ISSUE TITLE
Nested single list item of menu item do not behave as expected

### ISSUE THREAD

**Issue by jelhouss** [sakofchit/system.css#26]
Hi @sakofchit, nice job working on System.css, I am using it for my blog and I mentioned it as credits! Extremely happy! Thank you for the work. I use version **^0.1.9**

If I ever encounter any weird behavior, I override it. One of the things I encountered was using a menu that has an item that is lonely and does not have a nested menu. For example:

```
<ul role="menu-bar">
   <li role="menu-item" tabIndex={0} aria-haspopup="false"> <!-- this one -->
      <Link aria-label="home page" href="/">
      Home
      </Link>
   </li>
   <li role="menu-item" tabIndex={0} aria-haspopup="true">
      About
      <ul role="menu">
         <li role="menu-item">
            <Link aria-label="about page" href="/about">
            Me
            </Link>
         </li>
         <li role="menu-item">
            <Link aria-label="about page" href="/about-website">
            Website
            </Link>
         </li>
      </ul>
   </li>
</ul>
```

`Link` is the link (`a` tag) Next.js component. The menu works as expected. However, the first element has an attribute of `aria-haspopup="false"` because I have a single item which is an `a` children. If I use a plain list item like `<li>This is my single item as a plain item</li>` the menu item behaves as expected, but in cases to have a children for the list item, then it behaves differently (per child type, in my case an anchor tag).

Using `aria-haspopup="false"` has no effect so I had to override that:

```
ul[role="menu-bar"] li[aria-haspopup="false"] * {
  
  /* all tags */
  background-color: inherit;
  color: inherit;
  margin: 0;
  padding: 0;

  /* for a tags */
  text-decoration: none;
}
```

The expected behavior, in my opinion, is that if a list item contains a children (no matter what type) but does not have a nested menu, that list item should look like the other items.

Do you think that added code is semantically good to work with System.css? If so, should I open a PR and add this to be naturally implemented?
Or, am I off the road here and there is something I am missing?

**Comment by sakofchit** [comment]
Hi!

I really appreciate your breakdown of this.

> The expected behavior, in my opinion, is that if a list item contains a children (no matter what type) but does not have a nested menu, that list item should look like the other items.

I agree, this would make much more sense. If you'd like to open a PR for it that'd be swell and would much appreciated 🙏

**Comment by jelhouss** [comment]
Hi @sakofchit Thank you for your feedback, and I apologize for my late answer.

I am really busy currently. I don't know when I will be taking care of this. As this seems a very simple change to introduce, I will submit a PR with the code changes exactly similar to the code in the issue description unless there will be other code to consider which will require more attention for sure other than quick review. I am saying this just in case I took so long and someone else came through the same menu items issues and wanted to open a PR for it, as I believe the changes to introduce are simple and anyone is welcome to submit them, but I will do my best to come back to this.

However, I hope keeping the issue open will not disturb you.

**Comment by sakofchit** [comment]
> Hi @sakofchit Thank you for your feedback, and I apologize for my late answer.
> 
> I am really busy currently. I don't know when I will be taking care of this. As this seems a very simple change to introduce, I will submit a PR with the code changes exactly similar to the code in the issue description unless there will be other code to consider which will require more attention for sure other than quick review. I am saying this just in case I took so long and someone else came through the same menu items issues and wanted to open a PR for it, as I believe the changes to introduce are simple and anyone is welcome to submit them, but I will do my best to come back to this.
> 
> However, I hope keeping the issue open will not disturb you.

Perfectly fine! No rush :)

**Comment by jelhouss** [comment]
Hey @sakofchit

I hope these small changes are fine to introduce into the codebase despite the usage of `inherit` for colors and `*` for children. I believe it's safe as they also work with hovering and other states.
