### ISSUE TITLE
Menu navigation messes up documentation page layout

### ISSUE THREAD

**Issue by airarrazaval** [sakofchit/system.css#3]
When accessing https://sakofchit.github.io/system.css, if you navigate to the Intro section, the page layout suddenly expands making content be under the left menu window. If you try to go to any other menu link, the issue remains.

Steps to reproduce:

1. Go to https://sakofchit.github.io/system.css/#intro
2. Click on Intro in left menu
3. Try accessing any other section

Screenshots:

![image](https://user-images.githubusercontent.com/9391489/184357215-318ec639-eda0-4e88-8b50-a949d346b65d.png)

![image](https://user-images.githubusercontent.com/9391489/184357259-4fc0ff86-5283-4b2d-ac63-007911de66b0.png)

**Comment by sakofchit** [comment]
Hey, I [can't seem to reproduce this.](https://i.imgur.com/yWJCeMG.mp4). 

Also, what browser are you using? It looks like some stuff isn't being rendered properly in it as well

**Comment by CodeWhiteWeb** [comment]
I encountered the same issue but I got the problem 

Uploading system.css _ A design system for building retro Apple-inspired interfaces.mp4…

**Comment by CodeWhiteWeb** [comment]
I encountered the same Issue
reproduce the issue like this

https://user-images.githubusercontent.com/79645854/184495360-ad99be92-afba-40dc-a932-e700eb8a419b.mp4

**Comment by Preet-Sojitra** [comment]
I am using Firefox browser and I found the same issue. 
There is horinzontal overflow which is distorting the whole layout:
![image](https://user-images.githubusercontent.com/87543808/184502161-479a046e-8d60-469c-a3e5-032176f95053.png)
![image](https://user-images.githubusercontent.com/87543808/184502172-6b263bdb-2e70-41af-b000-b967d43e9709.png)

![image](https://user-images.githubusercontent.com/87543808/184502224-ecf181fb-e102-4f42-8542-b530b8a68b50.png)
This fixed width of `90rem` is creating trouble.  On removing the fixed width, site is rendering properly without any issues
![image](https://user-images.githubusercontent.com/87543808/184502259-43fb27f6-05b4-4f52-b4ba-265d97a32fbf.png)

If you don't mind, then I am ready to work on this issue and also fixing some other css

**Comment by sakofchit** [comment]
> If you don't mind, then I am ready to work on this issue and also fixing some other css

Go for it, and thank you for pointing that out 🙌

**Comment by MarketingPip** [comment]
Also came here just to report this! Very cool project @sakofchit - added to [Awesome-CSS-Resources: An awesome list of CSS / SCSS frameworks & resources.](https://github.com/MarketingPipeline/Awesome-CSS-Resources)

**Comment by freshyill** [comment]
This is pretty pronounced at mobile sizes. Additionally, it looks like there are some z-index issues with forms and possibly other elements.

![0CAD5890-F59F-4675-9244-5A559DCAF014](https://user-images.githubusercontent.com/879292/186899531-2fdfbe5e-8c96-4101-928e-7c765840c037.png)
