### ISSUE TITLE
less of a Issue and more of a question 

### ISSUE THREAD

**Issue by BagpipesRbetter** [sakofchit/system.css#30]
i want to have the body of my page be black but have a box with content have the defalt background img how would i do that i want it to look like how th origonal system6 running on a monitor with a black margin my current code looks like `<body style="background-color: #000000;display: flex;justify-content: center;background-image: none;">
    <div class="content" style="size: 90vw, 90vw;box-shadow: 0 0 20px rgba(0, 0, 0, 0.8);">` how would yall do this

somthing like this ![Screenshot 2023-08-21 at 7 34 21 PM](https://github.com/sakofchit/system.css/assets/119373672/b1532539-a2a0-4bd0-ad5b-7d3230e00870)

**Comment by BagpipesRbetter** [comment]
acutaly a better question would be how do you define the default background img in this framework

**Comment by sakofchit** [comment]
In the framework, the background/body is essentially defined as a pattern and not an image

https://github.com/sakofchit/system.css/blob/c95b95428021361eaa411ccb08fa3b1050cc606d/style.css#L143-L147

If you want to use your own background image/pattern you'd have to overwrite it.

**Comment by BagpipesRbetter** [comment]
hey did a little more reaserch and got it to do what i wanted this was the final result was 
![Screenshot 2023-08-24 at 3 04 54 PM](https://github.com/sakofchit/system.css/assets/119373672/cf0c81ea-ab50-49b3-a87a-7b4c3061ba24)the final code was 
`body {
background-image: none; background-color: #000000;
}
.pixel-corners { 
      --dot-bg: #ffffff;
      --dot-color: #000000;
      --dot-size: 1px;
      --dot-space: 22px;
      height: 90vh;
      padding-top: 0px;
      padding-left: 50px;
      padding-right: 50px;
      padding-bottom: 50px;
	    background:
		    linear-gradient(90deg, var(--dot-bg) calc(var(--dot-space) - var(--dot-size)), transparent 1%) center / var(--dot-space) var(--dot-space),
		    linear-gradient(var(--dot-bg) calc(var(--dot-space) - var(--dot-size)), transparent 1%) center / var(--dot-space) var(--dot-space),
		    var(--dot-color);;
      padding: 40px;
      overflow:hidden;
      position: relative;
      clip-path: polygon(
    0px calc(100% - 25px),
    5px calc(100% - 25px),
    5px calc(100% - 15px),
    10px calc(100% - 15px),
    10px calc(100% - 10px),
    15px calc(100% - 10px),
    15px calc(100% - 5px),
    25px calc(100% - 5px),
    25px 100%,
    calc(100% - 25px) 100%,
    calc(100% - 25px) calc(100% - 5px),
    calc(100% - 15px) calc(100% - 5px),
    calc(100% - 15px) calc(100% - 10px),
    calc(100% - 10px) calc(100% - 10px),
    calc(100% - 10px) calc(100% - 15px),
    calc(100% - 5px) calc(100% - 15px),
    calc(100% - 5px) calc(100% - 25px),
    100% calc(100% - 25px),
    100% 25px,
    calc(100% - 5px) 25px,
    calc(100% - 5px) 15px,
    calc(100% - 10px) 15px,
    calc(100% - 10px) 10px,
    calc(100% - 15px) 10px,
    calc(100% - 15px) 5px,
    calc(100% - 25px) 5px,
    calc(100% - 25px) 0px,
    25px 0px,
    25px 5px,
    15px 5px,
    15px 10px,
    10px 10px,
    10px 15px,
    5px 15px,
    5px 25px,
    0px 25px
  );}

<body class="body">
    <div class="pixel-corners">
#####rest of my code
    </div>
</body>`
