### ISSUE TITLE
Default Button Type

### ISSUE THREAD

**Issue by sakofchit** [sakofchit/system.css#8]
As seen from Apple's HI Guidelines:

<img width="504" alt="Screen Shot 2022-08-13 at 3 21 44 PM" src="https://user-images.githubusercontent.com/7917503/184507888-2160f9c8-df10-407b-b416-071217f1f4dd.png">

Buttons currently use the ```border-image``` property, so this could be achieved the same way.

**Comment by aryanh0911** [comment]
can you specify what needs to be done?

**Comment by sakofchit** [comment]
> can you specify what needs to be done?

Basically we'd need to create a new button type/class that allow's users to add button's that look like the 'Find' button.

It's trivial and can be done by creating a border-image that has a thicker outer border to the one seen here: https://github.com/sakofchit/system.css/blob/main/icon/button.png

**Comment by gazhay** [comment]
On the original mac systems the default button worked differently than implemented here.

In the image above the "Find" button would have only inverted the "inner" button - like a "normal" button.
Here the entire button including the "outer" area turns black (the area between find and the default border also)
